### ISSUE TITLE
Work with ESP FreeRTOS?

### ISSUE THREAD

**Issue by readysteadygo2006** [lws-team/esplws#1]
Hi,

Have you had any joy getting things to work with the ESP8266 Free RTOS SDK?

BR

**Comment by lws-team** [comment]
No I haven't tried it.

But this "OS" works fine, in fact I use it daily for some months.

The integration with that OS is not very heavy, it gets added to the build as
- raw lws git directory
- lws-glue that provides some generic integration

and you have to call an lws init function to make it work.  So I wouldn't expect it's that hard (if you are already used to ESP8266 general idiosyncrasies).
